# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.roastLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.roastLabel.setObjectName("roastLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.roastLabel)
        self.roastCombo = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.roastCombo.setObjectName("roastCombo")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.roastCombo.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.roastCombo)
        self.grindLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.grindLabel.setObjectName("grindLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.grindLabel)
        self.grindCombo = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.grindCombo.setObjectName("grindCombo")
        self.grindCombo.addItem("")
        self.grindCombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.grindCombo)
        self.tasteLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.tasteLabel.setObjectName("tasteLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.tasteLabel)
        self.tasteEdit = QtWidgets.QTextEdit(parent=AddEditCoffeeForm)
        self.tasteEdit.setObjectName("tasteEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tasteEdit)
        self.priceLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priceLabel)
        self.priceSpin = QtWidgets.QDoubleSpinBox(parent=AddEditCoffeeForm)
        self.priceSpin.setMinimum(0.0)
        self.priceSpin.setMaximum(10000.0)
        self.priceSpin.setObjectName("priceSpin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priceSpin)
        self.volumeLabel = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.volumeLabel.setObjectName("volumeLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.volumeLabel)
        self.volumeSpin = QtWidgets.QSpinBox(parent=AddEditCoffeeForm)
        self.volumeSpin.setMinimum(1)
        self.volumeSpin.setMaximum(5000)
        self.volumeSpin.setObjectName("volumeSpin")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.volumeSpin)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавление/Редактирование кофе"))
        self.nameLabel.setText(_translate("AddEditCoffeeForm", "Название сорта:"))
        self.roastLabel.setText(_translate("AddEditCoffeeForm", "Степень обжарки:"))
        self.roastCombo.setItemText(0, _translate("AddEditCoffeeForm", "Светлая"))
        self.roastCombo.setItemText(1, _translate("AddEditCoffeeForm", "Средняя"))
        self.roastCombo.setItemText(2, _translate("AddEditCoffeeForm", "Средне-темная"))
        self.roastCombo.setItemText(3, _translate("AddEditCoffeeForm", "Темная"))
        self.grindLabel.setText(_translate("AddEditCoffeeForm", "Тип помола:"))
        self.grindCombo.setItemText(0, _translate("AddEditCoffeeForm", "В зернах"))
        self.grindCombo.setItemText(1, _translate("AddEditCoffeeForm", "Молотый"))
        self.tasteLabel.setText(_translate("AddEditCoffeeForm", "Описание вкуса:"))
        self.priceLabel.setText(_translate("AddEditCoffeeForm", "Цена (руб):"))
        self.volumeLabel.setText(_translate("AddEditCoffeeForm", "Объем упаковки (г):"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddEditCoffeeForm = QtWidgets.QDialog()
    ui = Ui_AddEditCoffeeForm()
    ui.setupUi(AddEditCoffeeForm)
    AddEditCoffeeForm.show()
    sys.exit(app.exec())
